name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd web
          npm ci
          
      - name: Build (if needed)
        run: |
          cd web
          npm run build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: openmanus
          directory: web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: web
          
      - name: Deployment Status
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deployment completed successfully!"
          echo "Your site should be available at: https://openmanus.pages.dev"